### ISSUE TITLE
use uint16_t for color values

### ISSUE THREAD

**Issue by olikraus** [olikraus/U8g2_for_Adafruit_GFX#1]
Adafruit function calls look like this

drawFastVLine(int16_t x, int16_t y, int16_t h, uint16_t color),
drawFastHLine(int16_t x, int16_t y, int16_t w, uint16_t color),

Currently the code uses uint8_t

**Comment by olikraus** [comment]
done

**Comment by FrenchLab47** [comment]
That's it, thank you!
