### ISSUE TITLE
Successfully used with GxEPD2, 4.2" Waveshare ePaper

### ISSUE THREAD

**Issue by crteensy** [olikraus/U8g2_for_Adafruit_GFX#14]
Just a note about a library that is apparently supported: https://github.com/ZinggJM/GxEPD2

Platform: ESP8266 (nodemcu)
Display: 4.2" black/white Waveshare ePaper display
Fonts are apparently loaded to RAM, but that didn't really break anything.

**Comment by olikraus** [comment]
thanks for the feedback!
