### ISSUE TITLE
ESp32 1.0.3rc-1

### ISSUE THREAD

**Issue by G6EJD** [olikraus/U8g2_for_Adafruit_GFX#16]
Using ESP32 1.0.3rc-1 the compilation fails because 'sum' is not initialised

  int16_t sum, delta; // original source

I changed it to:

  int16_t **sum = 0**, delta;

And it then compiles and all works correctly.

**Comment by olikraus** [comment]
oh, nice finding... fixed.

**Comment by G6EJD** [comment]
Thanks, problem solved now the updated version installed.
