### ISSUE TITLE
Add bigger Cyrillic font(s) please

### ISSUE THREAD

**Issue by ZinggJM** [olikraus/U8g2_for_Adafruit_GFX#22]
Hi Oliver,

could you add bigger Cyrillic font(s) to u8g2 and U8g2_for_Adafruit_GFX?
Please see Arduino Forum Topic https://forum.arduino.cc/index.php?topic=644866.0

Thank you

Jean-Marc

**Comment by olikraus** [comment]
Hmmm the only option is to derive the gylphs from a ttf font. inconsolata contains cyrillic glyphs.
Whould this be ok? I can several sizes up to 62 pixel height...

![inr](https://user-images.githubusercontent.com/1084992/68527655-8fb71f80-02e9-11ea-97b3-d45079cd2931.png)

**Comment by olikraus** [comment]
ok, looks like the 62 pixel height version does not work. Will create up to 49 pixel height

**Comment by ZinggJM** [comment]
Thank you very much. As you see, this is not for me, and I am not a font expert. I am happy with anything you can provide.

**Comment by olikraus** [comment]
Yes, I know. It's done already, but I still have to update this project. Hope to do this over the weekend.
