### ISSUE TITLE
Euro sign in big font?

### ISSUE THREAD

**Issue by DerRudi63** [olikraus/U8g2_for_Adafruit_GFX#28]
I like to be able to print the euro sign '€' with a big font, say 24 or 30 px high. I searched the supported fonts, but was not able to find one. Smaller font sizes are available, but not a larger one it seems. 

Am I missing something? Or is there another solution?

**Comment by olikraus** [comment]
Glyph &#8364/&#x20AC seems to be part of the Adobe fonts but they are not they are not rendered. Probably you need to create a custom u8g2 font from a given bdf file.

**Comment by DerRudi63** [comment]
Thanks for the response. Unfortunatly I am not familiar with font creation. Do you have a link for me to follow, thanks.

**Comment by olikraus** [comment]
done
