### ISSUE TITLE
Can't get to work with multiple OLED connected with I2C Multiplexer

### ISSUE THREAD

**Issue by amritgenius** [olikraus/U8g2_for_Adafruit_GFX#43]
Hello All, i have this project where i need to use more than one displays with adafruit gfx library along with u8g2 fonts but still no luck, single display is working fine.

**Comment by olikraus** [comment]
Not sure how we can help here. Wouldn't it be better to ask Adafruit GFX project instead?
Maybe here: https://github.com/adafruit/Adafruit-GFX-Library

**Comment by amritgenius** [comment]
Hello Sir, Multiple Displays are working with solo Adafruit GFX lib but as soon as i impliment u8g2 for adafruit gfx, they stop working.

**Comment by olikraus** [comment]
Sounds like a RAM problem
